[DEFAULT]
NUMBER_OF_TILES = 7
WIDTH = 32
HEIGHT = 32
TILE_SIZE = 64
BG_COLOR = 120
BORDER_MODE = 1
IMAGE_PATH = "final.jpg"


[NORTH_SOUTH]
row1 = [true, false, false, true, true, false, true]
row2 = [false, true, true, false, false, true, false]
row3 = [true, false, false, true, true, false, true]
row4 = [false, true, true, false, false, true, false]
row5 = [false, true, true, false, false, true, false]
row6 = [true, false, false, true, true, false, true]
row7 = [true, false, false, true, true, false, true]

[EAST_WEST]
row1 = [true, false, true, true, false, false, false]
row2 = [false, true, false, false, true, true, true]
row3 = [false, true, false, false, true, true, true]
row4 = [false, true, false, false, true, true, true]
row5 = [true, false, true, true, false, false, false]
row6 = [true, false, true, true, false, false, false]
row7 = [false, true, false, false, true, true, true]

[TILES]
FOLDER = "./ex_tiles"
TILE_IMGS = ["0.png", "1.png", "2.png", "3.png", "4.png", "5.png", "6.png"]
